### PR TITLE
removed google login for now

### PR DESCRIPTION
**Pull request by mcdonnelldean**

### CODE REVIEW

**Comment by mirceaalexandru** [comment]
@mcdonnelldean 
I just wanted to add Twitter/Github login :(

**Comment by mcdonnelldean** [comment]
@mirceaalexandru It's just for a customer's demo, they can go back in on a branch. I'll be scripting their appearance soon.

**Comment by mirceaalexandru** [comment]
I want to discuss also about this with you, maybe Monday?

**Comment by mcdonnelldean** [comment]
Sounds good!

**Pull request merged**
